export const majorsOptions = [
  "All",
  "Arts",
  "Business",
  "Communication",
  "Journalism & Writing",
  "Computer Science & Information Technology",
  "Education",
  "Engineering",
  "Health Professions",
  "Humanities & Social Sciences",
  "Law & Legal Studies",
  "Mathematics & Natural Sciences",
  "Multidisciplinary Studies",
];
export const subMajors: Record<string, string[]> = {
  All: [
    "Visual Arts",
    "Performing Arts",
    "Music",
    "Design",
    "Film & Media Arts",
    "Accounting",
    "Finance",
    "Marketing",
    "Management",
    "Entrepreneurship",
    "International Business",
    "Public Relations",
    "Advertising",
    "Media Studies",
    "Digital Communication",
    "Print Journalism",
    "Broadcast Journalism",
    "Creative Writing",
    "Technical Writing",
    "Software Engineering",
    "Cybersecurity",
    "Data Science",
    "Artificial Intelligence",
    "Information Systems",
    "Early Childhood Education",
    "Secondary Education",
    "Special Education",
    "Educational Leadership",
    "Mechanical Engineering",
    "Electrical Engineering",
    "Civil Engineering",
    "Chemical Engineering",
    "Aerospace Engineering",
    "Biomedical Engineering",
    "Nursing",
    "Pharmacy",
    "Public Health",
    "Physical Therapy",
    "Dentistry",
    "Medicine",
    "History",
    "Philosophy",
    "Political Science",
    "Psychology",
    "Sociology",
    "Anthropology",
    "Criminal Justice",
    "International Law",
    "Corporate Law",
    "Constitutional Law",
    "Mathematics",
    "Statistics",
    "Physics",
    "Chemistry",
    "Biology",
    "Environmental Science",
    "Cognitive Science",
    "Data Analytics",
    "Environmental Studies",
    "Gender Studies",
    "Global Studies",
  ],
  Arts: [
    "Visual Arts",
    "Performing Arts",
    "Music",
    "Design",
    "Film & Media Arts",
  ],
  Business: [
    "Accounting",
    "Finance",
    "Marketing",
    "Management",
    "Entrepreneurship",
    "International Business",
  ],
  Communication: [
    "Public Relations",
    "Advertising",
    "Media Studies",
    "Digital Communication",
  ],
  "Journalism & Writing": [
    "Print Journalism",
    "Broadcast Journalism",
    "Creative Writing",
    "Technical Writing",
  ],
  "Computer Science & Information Technology": [
    "Software Engineering",
    "Cybersecurity",
    "Data Science",
    "Artificial Intelligence",
    "Information Systems",
  ],
  Education: [
    "Early Childhood Education",
    "Secondary Education",
    "Special Education",
    "Educational Leadership",
  ],
  Engineering: [
    "Mechanical Engineering",
    "Electrical Engineering",
    "Civil Engineering",
    "Chemical Engineering",
    "Aerospace Engineering",
    "Biomedical Engineering",
  ],
  "Health Professions": [
    "Nursing",
    "Pharmacy",
    "Public Health",
    "Physical Therapy",
    "Dentistry",
    "Medicine",
  ],
  "Humanities & Social Sciences": [
    "History",
    "Philosophy",
    "Political Science",
    "Psychology",
    "Sociology",
    "Anthropology",
  ],
  "Law & Legal Studies": [
    "Criminal Justice",
    "International Law",
    "Corporate Law",
    "Constitutional Law",
  ],
  "Mathematics & Natural Sciences": [
    "Mathematics",
    "Statistics",
    "Physics",
    "Chemistry",
    "Biology",
    "Environmental Science",
  ],
  "Multidisciplinary Studies": [
    "Cognitive Science",
    "Data Analytics",
    "Environmental Studies",
    "Gender Studies",
    "Global Studies",
  ],
};

export const careerOptions: Record<string, string[]> = {
  // ----- ARTS -----
  "Visual Arts": [
    "Painter",
    "Illustrator",
    "Art Director",
    "Museum Curator",
    "Gallery Manager",
  ],
  "Performing Arts": [
    "Actor",
    "Dancer",
    "Theater Director",
    "Choreographer",
    "Stage Manager",
  ],
  Music: [
    "Musician",
    "Composer",
    "Music Producer",
    "Sound Engineer",
    "Music Teacher",
  ],
  Design: [
    "Graphic Designer",
    "UX/UI Designer",
    "Product Designer",
    "Creative Director",
    "Industrial Designer",
  ],
  "Film & Media Arts": [
    "Filmmaker",
    "Cinematographer",
    "Editor",
    "Screenwriter",
    "Film Critic",
  ],

  // ----- BUSINESS -----
  Accounting: [
    "Auditor",
    "Tax Consultant",
    "Financial Analyst",
    "Forensic Accountant",
    "Controller",
  ],
  Finance: [
    "Investment Banker",
    "Portfolio Manager",
    "Financial Planner",
    "Risk Analyst",
    "Treasury Analyst",
  ],
  Marketing: [
    "Brand Manager",
    "Market Research Analyst",
    "Digital Marketer",
    "SEO Specialist",
    "Content Strategist",
  ],
  Management: [
    "Business Manager",
    "Project Manager",
    "Operations Manager",
    "HR Manager",
    "Strategy Consultant",
  ],
  Entrepreneurship: [
    "Startup Founder",
    "Business Consultant",
    "Product Manager",
    "Innovation Manager",
    "Venture Capital Analyst",
  ],
  "International Business": [
    "Export Manager",
    "Global Marketing Specialist",
    "International Trade Analyst",
    "Foreign Investment Advisor",
    "Supply Chain Manager",
  ],

  // ----- COMMUNICATION -----
  "Public Relations": [
    "PR Specialist",
    "Corporate Communications Manager",
    "Crisis Communication Consultant",
    "Media Relations Officer",
  ],
  Advertising: [
    "Advertising Executive",
    "Media Planner",
    "Copywriter",
    "Creative Director",
  ],
  "Media Studies": [
    "Media Analyst",
    "Broadcast Producer",
    "Content Strategist",
    "Media Policy Researcher",
  ],
  "Digital Communication": [
    "Social Media Manager",
    "Digital Strategist",
    "Content Creator",
    "Community Manager",
  ],

  // ----- JOURNALISM & WRITING -----
  "Print Journalism": [
    "Reporter",
    "Editor",
    "Investigative Journalist",
    "Magazine Writer",
  ],
  "Broadcast Journalism": [
    "News Anchor",
    "TV Reporter",
    "Radio Host",
    "Documentary Producer",
  ],
  "Creative Writing": ["Author", "Poet", "Screenwriter", "Editor"],
  "Technical Writing": [
    "Technical Writer",
    "Documentation Specialist",
    "Content Developer",
    "Proposal Writer",
  ],

  // ----- COMPUTER SCIENCE -----
  "Software Engineering": [
    "Software Developer",
    "Systems Architect",
    "Mobile App Developer",
    "DevOps Engineer",
  ],
  Cybersecurity: [
    "Security Analyst",
    "Penetration Tester",
    "Security Engineer",
    "Incident Responder",
  ],
  "Data Science": [
    "Data Analyst",
    "Machine Learning Engineer",
    "Data Engineer",
    "AI Researcher",
  ],
  "Artificial Intelligence": [
    "AI Engineer",
    "Robotics Specialist",
    "Computer Vision Engineer",
    "NLP Scientist",
  ],
  "Information Systems": [
    "Systems Analyst",
    "Database Administrator",
    "ERP Consultant",
    "IT Manager",
  ],

  // ----- EDUCATION -----
  "Early Childhood Education": [
    "Preschool Teacher",
    "Childcare Director",
    "Curriculum Designer",
    "Special Needs Educator",
  ],
  "Secondary Education": [
    "High School Teacher",
    "Curriculum Developer",
    "Educational Consultant",
    "School Administrator",
  ],
  "Special Education": [
    "Special Needs Teacher",
    "Behavior Analyst",
    "Learning Support Specialist",
    "Inclusion Coordinator",
  ],
  "Educational Leadership": [
    "Principal",
    "Superintendent",
    "Education Policy Analyst",
    "Instructional Coordinator",
  ],

  // ----- ENGINEERING -----
  "Mechanical Engineering": [
    "Mechanical Engineer",
    "Automotive Engineer",
    "Manufacturing Engineer",
    "Robotics Engineer",
  ],
  "Electrical Engineering": [
    "Electrical Engineer",
    "Power Systems Engineer",
    "Electronics Engineer",
    "Control Systems Engineer",
  ],
  "Civil Engineering": [
    "Structural Engineer",
    "Urban Planner",
    "Construction Manager",
    "Transportation Engineer",
  ],
  "Chemical Engineering": [
    "Process Engineer",
    "Pharmaceutical Engineer",
    "Materials Scientist",
    "Biochemical Engineer",
  ],
  "Aerospace Engineering": [
    "Aerospace Engineer",
    "Avionics Specialist",
    "Flight Test Engineer",
    "Spacecraft Designer",
  ],
  "Biomedical Engineering": [
    "Biomedical Engineer",
    "Clinical Engineer",
    "Medical Device Designer",
    "Rehabilitation Engineer",
  ],

  // ----- HEALTH PROFESSIONS -----
  Nursing: [
    "Registered Nurse",
    "Nurse Practitioner",
    "Clinical Nurse Specialist",
    "Public Health Nurse",
  ],
  Pharmacy: [
    "Pharmacist",
    "Clinical Pharmacist",
    "Pharmaceutical Researcher",
    "Regulatory Affairs Specialist",
  ],
  "Public Health": [
    "Epidemiologist",
    "Health Policy Analyst",
    "Public Health Educator",
    "Community Health Worker",
  ],
  "Physical Therapy": [
    "Physical Therapist",
    "Rehabilitation Specialist",
    "Sports Therapist",
    "Orthopedic Therapist",
  ],
  Dentistry: ["Dentist", "Orthodontist", "Oral Surgeon", "Dental Hygienist"],
  Medicine: ["Physician", "Surgeon", "Anesthesiologist", "Pediatrician"],

  // ----- HUMANITIES & SOCIAL SCIENCES -----
  History: [
    "Historian",
    "Museum Archivist",
    "Historical Researcher",
    "Educator",
  ],
  Philosophy: ["Ethicist", "Policy Advisor", "Philosophy Professor", "Author"],
  "Political Science": [
    "Policy Analyst",
    "Political Consultant",
    "Diplomat",
    "Legislative Aide",
  ],
  Psychology: [
    "Clinical Psychologist",
    "Counselor",
    "Industrial-Organizational Psychologist",
    "Neuropsychologist",
  ],
  Sociology: [
    "Sociologist",
    "Community Development Specialist",
    "Social Researcher",
    "Policy Analyst",
  ],
  Anthropology: [
    "Archaeologist",
    "Cultural Anthropologist",
    "Forensic Anthropologist",
    "Museum Curator",
  ],

  // ----- LAW & LEGAL STUDIES -----
  "Criminal Justice": [
    "Police Officer",
    "Corrections Officer",
    "Criminologist",
    "FBI Agent",
  ],
  "International Law": [
    "International Lawyer",
    "Diplomat",
    "Human Rights Advocate",
    "Trade Law Specialist",
  ],
  "Corporate Law": [
    "Corporate Lawyer",
    "Compliance Officer",
    "Mergers & Acquisitions Specialist",
    "Legal Advisor",
  ],
  "Constitutional Law": [
    "Constitutional Lawyer",
    "Civil Rights Attorney",
    "Legal Scholar",
    "Policy Advocate",
  ],

  // ----- MATH & NATURAL SCIENCES -----
  Mathematics: [
    "Mathematician",
    "Actuary",
    "Data Scientist",
    "Operations Research Analyst",
  ],
  Statistics: [
    "Statistician",
    "Biostatistician",
    "Data Analyst",
    "Market Research Analyst",
  ],
  Physics: [
    "Physicist",
    "Astrophysicist",
    "Nuclear Physicist",
    "Research Scientist",
  ],
  Chemistry: [
    "Chemist",
    "Pharmaceutical Chemist",
    "Forensic Chemist",
    "Materials Chemist",
  ],
  Biology: ["Biologist", "Geneticist", "Microbiologist", "Marine Biologist"],
  "Environmental Science": [
    "Environmental Scientist",
    "Ecologist",
    "Conservation Scientist",
    "Sustainability Consultant",
  ],

  // ----- MULTIDISCIPLINARY -----
  "Cognitive Science": [
    "Cognitive Scientist",
    "AI Researcher",
    "Human Factors Specialist",
    "UX Researcher",
  ],
  "Data Analytics": [
    "Data Analyst",
    "Business Intelligence Analyst",
    "Data Engineer",
    "Machine Learning Specialist",
  ],
  "Environmental Studies": [
    "Environmental Planner",
    "Climate Policy Analyst",
    "Sustainability Officer",
    "Wildlife Conservationist",
  ],
  "Gender Studies": [
    "Gender Policy Analyst",
    "Social Worker",
    "Human Rights Advocate",
    "Community Organizer",
  ],
  "Global Studies": [
    "International Relations Specialist",
    "Foreign Service Officer",
    "NGO Coordinator",
    "Development Consultant",
  ],
};

export const languagesOptions = [
  "English",
  "Turkish",
  "Spanish",
  "French",
  "German",
  "Italian",
  "Portuguese",
  "Russian",
  "Chinese",
  "Japanese",
  "Korean",
  "Arabic",
  "Hindi",
  "Bengali",
  "Urdu",
  "Persian",
  "Dutch",
  "Swedish",
  "Norwegian",
  "Danish",
  "Finnish",
  "Polish",
  "Czech",
  "Greek",
  "Hebrew",
  "Thai",
  "Vietnamese",
  "Indonesian",
  "Malay",
  "Swahili",
];
